import type { Metadata } from "next";
import "./globals.css";
import '@fontsource-variable/dm-sans';


export const metadata: Metadata = {
  title: "Simple Coffee Listing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
